---

- name: Update apt sources
  apt:
    update_cache: yes
    cache_valid_time: 600
  register: apt_update
  until: apt_update|success
  tags: apt-mirror-install

- name: Install apt-mirror package
  apt:
    pkg: apt-mirror
    state: latest
  register: install_packages
  until: install_packages|success
  tags: apt-mirror-install
